ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# build arguments for external artifacts
# ARG MYSQL_CONNECTOR_VERSION=8.0.23

# add MySQL JDBC connector to server home as a third party library
# ADD --chown=wso2carbon:wso2 https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_CONNECTOR_VERSION}/mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar ${WSO2_SERVER_HOME}/repository/components/dropins/

# copy extensions to API-M server home
# COPY dropins ${WSO2_SERVER_HOME}/repository/components/dropins/

# copy libs to API-M server home
# COPY lib ${WSO2_SERVER_HOME}/repository/components/lib/
